[package]
name = "wasmtime_ex"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "wasmtime_ex"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.1"
serde = "1.0.118"
serde_json = "1.0"
lazy_static = "1.0"
wasmtime = "0.21.0"
crossbeam = "0.6.0"
